version: '3'

services:
  server:
    build:
      context: ""
      dockerfile: deployment/Dockerfile
      args:
        cmd: server
    image: server:latest

    volumes:
      - /home/artem/videos/:/mnt/videos
    ports:
      - 1111:1111
    environment:
      - ADDR=:1111
      - RESULT_PATH=/mnt/videos

  worker:
    build:
      context: ""
      dockerfile: deployment/Dockerfile
      args:
        cmd: client
    image: worker:latest
    depends_on:
      - server
    environment:
      - SERVER_ADDR=http://server:1111